name: Dockerized Test Workflow

on: [push]

jobs:
  build:
    name: test-code
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Test code in Docker container	    
        uses: docker://continuumio/anaconda3:2020.11
        with:
          args: pytest --verbose test_pa1.py